### ISSUE TITLE
Update user-storage-jpa to work with the new distribution

### ISSUE THREAD

**Issue by pedroigor** [keycloak/keycloak-quickstarts#303]
### Describe the bug

Currently, it is not possible to run the `user-storage-jpa` quickstart due to https://github.com/keycloak/keycloak/issues/10579.

We should update the quickstart to make it work with the new distribution while still keeping the module used to run the quickstart in the legacy distribution.

### Version

17.0.0

**Comment by ahus1** [comment]
There is now a PR for this: #302

**Comment by pedroigor** [comment]
@ahus1 Thanks.

**Comment by marcelnem** [comment]
Will jpa user connector be supported only from keycloak 18? What should we do in the meantime if we want to update to keycloak 17 and we currently use User federation jpa on wildfly? Does it mean we have to wait till Keycloak 18 to switch to Quarkus?

Next to a new example, it would be also good to summarise steps to migrate existing providers. We spent a lot of time writing our DB user connector for wildfly, starting from a quarkus basic example might still be some work. For example it would be helpful to summarise changes such as that entity manager has to be initialized in a different way and other limitations of quarkus. In other words, the new example is useful for projects which start from scratch, but eventually all keycloak projects will have to migrate to quarkus, so the existing user storage providers in these organisations will have to be migrated to work with quarkus.

Maybe it is enough to look at the https://github.com/keycloak/keycloak-quickstarts/pull/302/files differences and apply the same differences to my provider, but this requires reverse engineering. A simple guide with the know-how from @pedroigor  could save us time figuring out the same problems that he had to solve to migrate the user-storage-jpa example code. 

The reverse engineering / comparing of files is not straightforward because the files are named differently and are moved to a different folder. I will have to do a diff from the previous UserAdapter to the new UserAdapter to see the actual changes I need to apply to my project.

Do these docs also need to be updated or are they independent of wildfly/quarkus or already updated for quarkus? 
https://www.keycloak.org/docs/latest/server_development/index.html#_user-storage-spi

**Comment by pedroigor** [comment]
@marcelnem You are right, the experience is not the best right now. We are trying to provide as much information as we can and possibly create some guides.

You should be able to use an additional datasouce/persistence unit starting from 17.0.1.

**Comment by DGuhr** [comment]
Closing here, as the new example is available under https://github.com/keycloak/keycloak-quickstarts/tree/main/user-storage-jpa - for a specific migration guide, I'd like to hear more specific problems first that we could address in that guide, after having that information let's create a new issue to create that guide.

**Comment by marcelnem** [comment]
I was able to upgrade our user storage connector based on the example from @pedroigor pull request. 


I did a diff between old code and the new example. 
The little problems which I had to overcome were related to:
 DB config (choosing SQL dialect) in persisence.xml
Changing how Entity Manager is initialized.
Removing JEE annotations
Updating deprecated interfaces to the new ones.
